### ISSUE TITLE
Timeout argument doesn't take string

### ISSUE THREAD

**Issue by benhocker** [nickanderson/check_snmp_extend#2]
I'm probably doing something wrong but I was getting the below error when I used the timeout argument.  

<pre><code>
Traceback (most recent call last):
  File "./check_snmp_extend.py", line 497, in <module>
    main()
  File "./check_snmp_extend.py", line 449, in main
    do_the_main_stuff()
  File "./check_snmp_extend.py", line 87, in f2
    signal.alarm(options.timeout) # triger alarm in timeout_time seconds
</code></pre>

I just added an <code> int() </code> around it and it seemed to work after that:

<code>
signal.alarm(int(options.timeout)) # triger alarm in timeout_time seconds
</code>

**Comment by severinsimko** [comment]
I have exactly same problem, how did you fix it ?

**Comment by benhocker** [comment]
It looks like i just forced the options.timeout to an integer on [this line](https://github.com/nickanderson/check_snmp_extend/blob/master/check_snmp_extend.py#L87):

from:

```
signal.alarm(options.timeout) # triger alarm in timeout_time seconds
```

to:

```
signal.alarm(int(options.timeout)) # triger alarm in timeout_time seconds 
```
